config/routes.rb
Rails.application.routes.draw do
  resources :followings
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Thredded::Engine => '/forum'
  mount ActionCable.server => '/cable'
  get '/private_topic', to: 'thredded/private_topics#index'
  put '/mark_read', to: 'thredded/private_topics#mark_read'

  resources :notifications do
    member do
      get :mark_as_read
    end
  end

  resources :followings, only: %w(new create destroy)
  resources :searches
  resources :options
  resources :users
  resources :homes do
    resources :reviews
    resources :photos
  end
  resources :conversations do
    resources :messages
  end
  resources :home_steps

  root 'homes#index'
  get  '/forum', to: 'comments#index'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'auth/:provider/callback', to: 'sessions#create_omni'
  get 'auth/failure', to: redirect('/')
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :user
  belongs_to :home
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  before_action :set_following, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:new, :create]

  # GET /followings
  # GET /followings.json
  def index
    @followings = Following.all
  end

  # GET /followings/1
  # GET /followings/1.json
  def show
  end

  # GET /followings/new
  def new
    @following = Following.new
  end

  # GET /followings/1/edit
  def edit
  end

  # POST /followings
  # POST /followings.json
  def create
    @following = Following.new(home_id: following_params[:home_id], user_id: current_user.id)
    respond_to do |format|
      if(@following.save)
        format.js { render :create, locals: {home: @following.home} }
      else
        format.html { redirect_to root_url, notice: "Unsuccessful" }
        format.json { render json: @following.errors, status: :unprocessable_entity }
      end

    end
  end

  # PATCH/PUT /followings/1
  # PATCH/PUT /followings/1.json
  def update
    respond_to do |format|
      if @following.update(following_params)
        format.html { redirect_to @following, notice: 'Following was successfully updated.' }
        format.json { render :show, status: :ok, location: @following }
      else
        format.html { render :edit }
        format.json { render json: @following.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /followings/1
  # DELETE /followings/1.json
  def destroy
    @following.destroy
    respond_to do |format|
      format.js { render :destroy, locals: {home: @following.home} }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_following
      @following = Following.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def following_params
      params.require(:following)
    end
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/views/followings/_form.html.erb
<%= form_with(model: following, local: true) do |form| %>
  <% if following.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(following.errors.count, "error") %> prohibited this following from being saved:</h2>

      <ul>
      <% following.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :following_user_id %>
  </div>

  <div class="field">
    <%= form.label :home_id %>
    <%= form.number_field :home_id, id: :following_home_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/followings/create.js.erb
$('#heart2-<%=home.id%>').replaceWith("<%=j link_to_toggle_post_favorite(home) %>");

app/views/followings/destroy.js.erb
$('#heart-<%=home.id%>').replaceWith("<%=j link_to_toggle_post_favorite(home) %>");
$('#home-<%=home.id%>').hide();

app/views/followings/edit.html.erb
<h1>Editing Following</h1>

<%= render 'form', following: @following %>

<%= link_to 'Show', @following %> |
<%= link_to 'Back', followings_path %>

app/views/followings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Followings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Home</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @followings.each do |following| %>
      <tr>
        <td><%= following.user_id %></td>
        <td><%= following.home_id %></td>
        <td><%= link_to 'Show', following %></td>
        <td><%= link_to 'Edit', edit_following_path(following) %></td>
        <td><%= link_to 'Destroy', following, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Following', new_following_path %>

app/views/followings/new.html.erb
<h1>New Following</h1>

<%= render 'form', following: @following %>

<%= link_to 'Back', followings_path %>

app/views/followings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @following.user_id %>
</p>

<p>
  <strong>Home:</strong>
  <%= @following.home_id %>
</p>

<%= link_to 'Edit', edit_following_path(@following) %> |
<%= link_to 'Back', followings_path %>