config/routes.rb
Rails.application.routes.draw do
  resources :followings
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Thredded::Engine => '/forum'
  mount ActionCable.server => '/cable'
  get '/private_topic', to: 'thredded/private_topics#index'
  put '/mark_read', to: 'thredded/private_topics#mark_read'

  resources :notifications do
    member do
      get :mark_as_read
    end
  end

  resources :followings, only: %w(new create destroy)
  resources :searches
  resources :options
  resources :users
  resources :homes do
    resources :reviews
    resources :photos
  end
  resources :conversations do
    resources :messages
  end
  resources :home_steps

  root 'homes#index'
  get  '/forum', to: 'comments#index'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'auth/:provider/callback', to: 'sessions#create_omni'
  get 'auth/failure', to: redirect('/')
end

app/views/comments/_form.html.erb
<%= form_for @comment do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, id: :comment_text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Forum</h1>


  <tbody>
    <% @comments.each do |comment| %>
        <br>
        <td> <strong><%= comment.text %></strong></td>
        <br>
        <td>By <i><%=comment.user.name%></i> </td>
        <br>
        <td> At <small><%=comment.updated_at%></small> </td>
        <%if comment.user==current_user%>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <br>
        <%end%>
        <br>
        <br>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment%>
<%= link_to 'Back', root_url %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @comment.text %>
</p>

  <td><%= link_to 'Edit', edit_comment_path(@comment) %></td>
<%= link_to 'Back', comments_path %>