config/routes.rb
Rails.application.routes.draw do
  resources :followings
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Thredded::Engine => '/forum'
  mount ActionCable.server => '/cable'
  get '/private_topic', to: 'thredded/private_topics#index'
  put '/mark_read', to: 'thredded/private_topics#mark_read'

  resources :notifications do
    member do
      get :mark_as_read
    end
  end

  resources :followings, only: %w(new create destroy)
  resources :searches
  resources :options
  resources :users
  resources :homes do
    resources :reviews
    resources :photos
  end
  resources :conversations do
    resources :messages
  end
  resources :home_steps

  root 'homes#index'
  get  '/forum', to: 'comments#index'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'auth/:provider/callback', to: 'sessions#create_omni'
  get 'auth/failure', to: redirect('/')
end

app/views/conversations/index.html.erb
<h1>All Conversations</h1>
<% @conversations.each do |conversation| %>
  <div>
    <%= link_to conversation.subject, conversation_path(conversation) %>
  </div>
<% end %>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= form_tag conversations_path(user_id: @recipient.id), method: :post do %>
  <div>
    <%= @recipient.email %>
  </div>

  <div>
    <%= text_field_tag :subject, @home_address %>
  </div>

  <div>
    <%= text_area_tag :body, nil, placeholder: "Leave a message" %>
  </div>

  <%= submit_tag "Send" %>
<% end %>

app/views/conversations/show.html.erb
<h1><%= @conversation.subject %></h1>

<% @conversation.receipts_for(current_user).each do |receipt| %>
  <div>
    <div><%= receipt.message.sender.name %> commented:</div>
    <p><%= receipt.message.body %></p>
  </div>
<% end %>

<%= form_tag conversation_messages_path(@conversation), method: :post do %>
  <div>
    <%= text_area_tag :body %>
  </div>

  <%= submit_tag "Send" %>
<% end %>