config/routes.rb
Rails.application.routes.draw do
  resources :followings
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Thredded::Engine => '/forum'
  mount ActionCable.server => '/cable'
  get '/private_topic', to: 'thredded/private_topics#index'
  put '/mark_read', to: 'thredded/private_topics#mark_read'

  resources :notifications do
    member do
      get :mark_as_read
    end
  end

  resources :followings, only: %w(new create destroy)
  resources :searches
  resources :options
  resources :users
  resources :homes do
    resources :reviews
    resources :photos
  end
  resources :conversations do
    resources :messages
  end
  resources :home_steps

  root 'homes#index'
  get  '/forum', to: 'comments#index'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'auth/:provider/callback', to: 'sessions#create_omni'
  get 'auth/failure', to: redirect('/')
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :home
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :set_option, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:show, :edit, :update, :destroy]

  def index
    @options = Option.all
  end

  # GET /options/1/edit
  def edit
  end

  # POST /options
  # POST /options.json
  def create
    @option = Option.new(option_params)

    respond_to do |format|
      if @option.save
        format.html { redirect_to @option }
        format.json { render :show, status: :created, location: @option }
      else
        format.html { render :new }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /options/1
  # PATCH/PUT /options/1.json
  def update
    respond_to do |format|
      if @option.update(option_params)
        format.html { redirect_to @option.home, notice: 'Option was successfully updated.' }
        format.json { render :show, status: :ok, location: @option.home }
      else
        format.html { render "homes/edit" }
        format.json { render json: @option.home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    @option.destroy
    respond_to do |format|
      format.html { redirect_to options_url, notice: 'Option was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option
      @option = Option.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def option_params
      params.require(:option).permit(:free_parking, :street_parking, :deposit, :broker, :pets, :heated, :ac, :tv, :dryer, :dish_washer, :fireplace, :kitchen, :garbage_disposal, :wireless, :lock, :elevator, :pool, :gym, :wheelchair, :hot_tub, :smoking, :events, :subletting, :utilities_included, :water_price, :heat_price, :closet, :porch, :lawn, :patio, :storage, :floors, :refrigerator, :stove, :microwave, :laundry, :laundry_free, :bike, :soundproof, :intercom, :gated, :doorman, :house, :apartment, home_attributes:[:id, :user_id, :notification_id, :description, :title, :address, :price, :start_date, :end_date, :total_rooms, :available_rooms, :available_beds, :total_bathrooms, :private_bathrooms, :is_furnished])
    end
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/views/options/_form.html.erb
<%= form_with(model: option, local: true) do |form| %>
  <% if option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(option.errors.count, "error") %> prohibited this option from being saved:</h2>

      <ul>
      <% option.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :free_parking %>
    <%= form.check_box :free_parking, id: :option_free_parking %>
  </div>

  <div class="field">
    <%= form.label :street_parking %>
    <%= form.check_box :street_parking, id: :option_street_parking %>
  </div>

  <div class="field">
    <%= form.label :deposit %>
    <%= form.text_field :deposit, id: :option_deposit %>
  </div>

  <div class="field">
    <%= form.label :broker %>
    <%= form.text_field :broker, id: :option_broker %>
  </div>

  <div class="field">
    <%= form.label :pets %>
    <%= form.check_box :pets, id: :option_pets %>
  </div>

  <div class="field">
    <%= form.label :beds %>
    <%= form.text_field :beds, id: :option_beds %>
  </div>

  <div class="field">
    <%= form.label :heated %>
    <%= form.check_box :heated, id: :option_heated %>
  </div>

  <div class="field">
    <%= form.label :ac %>
    <%= form.check_box :ac, id: :option_ac %>
  </div>

  <div class="field">
    <%= form.label :tv %>
    <%= form.check_box :tv, id: :option_tv %>
  </div>

  <div class="field">
    <%= form.label :dryer %>
    <%= form.check_box :dryer, id: :option_dryer %>
  </div>

  <div class="field">
    <%= form.label :dish_washer %>
    <%= form.check_box :dish_washer, id: :option_dish_washer %>
  </div>

  <div class="field">
    <%= form.label :fireplace %>
    <%= form.check_box :fireplace, id: :option_fireplace %>
  </div>

  <div class="field">
    <%= form.label :kitchen %>
    <%= form.check_box :kitchen, id: :option_kitchen %>
  </div>

  <div class="field">
    <%= form.label :garbage_disposal %>
    <%= form.check_box :garbage_disposal, id: :option_garbage_disposal %>
  </div>

  <div class="field">
    <%= form.label :wireless %>
    <%= form.check_box :wireless, id: :option_wireless %>
  </div>

  <div class="field">
    <%= form.label :lock %>
    <%= form.check_box :lock, id: :option_lock %>
  </div>

  <div class="field">
    <%= form.label :elevator %>
    <%= form.check_box :elevator, id: :option_elevator %>
  </div>

  <div class="field">
    <%= form.label :pool %>
    <%= form.check_box :pool, id: :option_pool %>
  </div>

  <div class="field">
    <%= form.label :gym %>
    <%= form.check_box :gym, id: :option_gym %>
  </div>

  <div class="field">
    <%= form.label :wheelchair %>
    <%= form.check_box :wheelchair, id: :option_wheelchair %>
  </div>

  <div class="field">
    <%= form.label :hot_tub %>
    <%= form.check_box :hot_tub, id: :option_hot_tub %>
  </div>

  <div class="field">
    <%= form.label :smoking %>
    <%= form.check_box :smoking, id: :option_smoking %>
  </div>

  <div class="field">
    <%= form.label :events %>
    <%= form.check_box :events, id: :option_events %>
  </div>

  <div class="field">
    <%= form.label :subletting %>
    <%= form.check_box :subletting, id: :option_subletting %>
  </div>

  <div class="field">
    <%= form.label :utilities_included %>
    <%= form.check_box :utilities_included, id: :option_utilities_included %>
  </div>

  <div class="field">
    <%= form.label :water_price %>
    <%= form.text_field :water_price, id: :option_water_price %>
  </div>

  <div class="field">
    <%= form.label :heat_price %>
    <%= form.text_field :heat_price, id: :option_heat_price %>
  </div>

  <div class="field">
    <%= form.label :closet %>
    <%= form.check_box :closet, id: :option_closet %>
  </div>

  <div class="field">
    <%= form.label :porch %>
    <%= form.check_box :porch, id: :option_porch %>
  </div>

  <div class="field">
    <%= form.label :lawn %>
    <%= form.check_box :lawn, id: :option_lawn %>
  </div>

  <div class="field">
    <%= form.label :patio %>
    <%= form.check_box :patio, id: :option_patio %>
  </div>

  <div class="field">
    <%= form.label :storage %>
    <%= form.check_box :storage, id: :option_storage %>
  </div>

  <div class="field">
    <%= form.label :floors %>
    <%= form.number_field :floors, id: :option_floors %>
  </div>

  <div class="field">
    <%= form.label :refrigerator %>
    <%= form.check_box :refrigerator, id: :option_refrigerator %>
  </div>

  <div class="field">
    <%= form.label :stove %>
    <%= form.check_box :stove, id: :option_stove %>
  </div>

  <div class="field">
    <%= form.label :microwave %>
    <%= form.check_box :microwave, id: :option_microwave %>
  </div>

  <div class="field">
    <%= form.label :laundry %>
    <%= form.check_box :laundry, id: :option_laundry %>
  </div>

  <div class="field">
    <%= form.label :laundry_free %>
    <%= form.check_box :laundry_free, id: :option_laundry_free %>
  </div>

  <div class="field">
    <%= form.label :bike %>
    <%= form.check_box :bike, id: :option_bike %>
  </div>

  <div class="field">
    <%= form.label :soundproof %>
    <%= form.check_box :soundproof, id: :option_soundproof %>
  </div>

  <div class="field">
    <%= form.label :intercom %>
    <%= form.check_box :intercom, id: :option_intercom %>
  </div>

  <div class="field">
    <%= form.label :gated %>
    <%= form.check_box :gated, id: :option_gated %>
  </div>

  <div class="field">
    <%= form.label :doorman %>
    <%= form.check_box :doorman, id: :option_doorman %>
  </div>

  <div class="field">
    <%= form.label :house %>
    <%= form.check_box :house, id: :option_house %>
  </div>

  <div class="field">
    <%= form.label :apartment %>
    <%= form.check_box :apartment, id: :option_apartment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/options/edit.html.erb
<h1>Editing Option</h1>

<%= render 'form', option: @option %>

<%= link_to 'Show', @option %> |
<%= link_to 'Back', options_path %>

app/views/options/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Options</h1>

<table>
  <thead>
    <tr>
      <th>Free parking</th>
      <th>Street parking</th>
      <th>Deposit</th>
      <th>Broker</th>
      <th>Pets</th>
      <th>Beds</th>
      <th>Heated</th>
      <th>Ac</th>
      <th>Tv</th>
      <th>Dryer</th>
      <th>Dish washer</th>
      <th>Fireplace</th>
      <th>Kitchen</th>
      <th>Garbage disposal</th>
      <th>Wireless</th>
      <th>Lock</th>
      <th>Elevator</th>
      <th>Pool</th>
      <th>Gym</th>
      <th>Wheelchair</th>
      <th>Hot tub</th>
      <th>Smoking</th>
      <th>Events</th>
      <th>Subletting</th>
      <th>Utilities included</th>
      <th>Water price</th>
      <th>Heat price</th>
      <th>Closet</th>
      <th>Porch</th>
      <th>Lawn</th>
      <th>Patio</th>
      <th>Storage</th>
      <th>Floors</th>
      <th>Refrigerator</th>
      <th>Stove</th>
      <th>Microwave</th>
      <th>Laundry</th>
      <th>Laundry free</th>
      <th>Bike</th>
      <th>Soundproof</th>
      <th>Intercom</th>
      <th>Gated</th>
      <th>Doorman</th>
      <th>House</th>
      <th>Apartment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @options.each do |option| %>
      <tr>
        <td><%= option.free_parking %></td>
        <td><%= option.street_parking %></td>
        <td><%= option.deposit %></td>
        <td><%= option.broker %></td>
        <td><%= option.pets %></td>
        <td><%= option.beds %></td>
        <td><%= option.heated %></td>
        <td><%= option.ac %></td>
        <td><%= option.tv %></td>
        <td><%= option.dryer %></td>
        <td><%= option.dish_washer %></td>
        <td><%= option.fireplace %></td>
        <td><%= option.kitchen %></td>
        <td><%= option.garbage_disposal %></td>
        <td><%= option.wireless %></td>
        <td><%= option.lock %></td>
        <td><%= option.elevator %></td>
        <td><%= option.pool %></td>
        <td><%= option.gym %></td>
        <td><%= option.wheelchair %></td>
        <td><%= option.hot_tub %></td>
        <td><%= option.smoking %></td>
        <td><%= option.events %></td>
        <td><%= option.subletting %></td>
        <td><%= option.utilities_included %></td>
        <td><%= option.water_price %></td>
        <td><%= option.heat_price %></td>
        <td><%= option.closet %></td>
        <td><%= option.porch %></td>
        <td><%= option.lawn %></td>
        <td><%= option.patio %></td>
        <td><%= option.storage %></td>
        <td><%= option.floors %></td>
        <td><%= option.refrigerator %></td>
        <td><%= option.stove %></td>
        <td><%= option.microwave %></td>
        <td><%= option.laundry %></td>
        <td><%= option.laundry_free %></td>
        <td><%= option.bike %></td>
        <td><%= option.soundproof %></td>
        <td><%= option.intercom %></td>
        <td><%= option.gated %></td>
        <td><%= option.doorman %></td>
        <td><%= option.house %></td>
        <td><%= option.apartment %></td>
        <td><%= link_to 'Show', option %></td>
        <td><%= link_to 'Edit', edit_option_path(option) %></td>
        <td><%= link_to 'Destroy', option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Option', new_option_path %>

app/views/options/new.html.erb
<h1>New Option</h1>

<%= render 'form', option: @option %>

<%= link_to 'Back', option_path %>

app/views/options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Free parking:</strong>
  <%= @option.free_parking %>
</p>

<p>
  <strong>Street parking:</strong>
  <%= @option.street_parking %>
</p>

<p>
  <strong>Deposit:</strong>
  <%= @option.deposit %>
</p>

<p>
  <strong>Broker:</strong>
  <%= @option.broker %>
</p>

<p>
  <strong>Pets:</strong>
  <%= @option.pets %>
</p>

<p>
  <strong>Beds:</strong>
  <%= @option.beds %>
</p>

<p>
  <strong>Heated:</strong>
  <%= @option.heated %>
</p>

<p>
  <strong>Ac:</strong>
  <%= @option.ac %>
</p>

<p>
  <strong>Tv:</strong>
  <%= @option.tv %>
</p>

<p>
  <strong>Dryer:</strong>
  <%= @option.dryer %>
</p>

<p>
  <strong>Dish washer:</strong>
  <%= @option.dish_washer %>
</p>

<p>
  <strong>Fireplace:</strong>
  <%= @option.fireplace %>
</p>

<p>
  <strong>Kitchen:</strong>
  <%= @option.kitchen %>
</p>

<p>
  <strong>Garbage disposal:</strong>
  <%= @option.garbage_disposal %>
</p>

<p>
  <strong>Wireless:</strong>
  <%= @option.wireless %>
</p>

<p>
  <strong>Lock:</strong>
  <%= @option.lock %>
</p>

<p>
  <strong>Elevator:</strong>
  <%= @option.elevator %>
</p>

<p>
  <strong>Pool:</strong>
  <%= @option.pool %>
</p>

<p>
  <strong>Gym:</strong>
  <%= @option.gym %>
</p>

<p>
  <strong>Wheelchair:</strong>
  <%= @option.wheelchair %>
</p>

<p>
  <strong>Hot tub:</strong>
  <%= @option.hot_tub %>
</p>

<p>
  <strong>Smoking:</strong>
  <%= @option.smoking %>
</p>

<p>
  <strong>Events:</strong>
  <%= @option.events %>
</p>

<p>
  <strong>Subletting:</strong>
  <%= @option.subletting %>
</p>

<p>
  <strong>Utilities included:</strong>
  <%= @option.utilities_included %>
</p>

<p>
  <strong>Water price:</strong>
  <%= @option.water_price %>
</p>

<p>
  <strong>Heat price:</strong>
  <%= @option.heat_price %>
</p>

<p>
  <strong>Closet:</strong>
  <%= @option.closet %>
</p>

<p>
  <strong>Porch:</strong>
  <%= @option.porch %>
</p>

<p>
  <strong>Lawn:</strong>
  <%= @option.lawn %>
</p>

<p>
  <strong>Patio:</strong>
  <%= @option.patio %>
</p>

<p>
  <strong>Storage:</strong>
  <%= @option.storage %>
</p>

<p>
  <strong>Floors:</strong>
  <%= @option.floors %>
</p>

<p>
  <strong>Refrigerator:</strong>
  <%= @option.refrigerator %>
</p>

<p>
  <strong>Stove:</strong>
  <%= @option.stove %>
</p>

<p>
  <strong>Microwave:</strong>
  <%= @option.microwave %>
</p>

<p>
  <strong>Laundry:</strong>
  <%= @option.laundry %>
</p>

<p>
  <strong>Laundry free:</strong>
  <%= @option.laundry_free %>
</p>

<p>
  <strong>Bike:</strong>
  <%= @option.bike %>
</p>

<p>
  <strong>Soundproof:</strong>
  <%= @option.soundproof %>
</p>

<p>
  <strong>Intercom:</strong>
  <%= @option.intercom %>
</p>

<p>
  <strong>Gated:</strong>
  <%= @option.gated %>
</p>

<p>
  <strong>Doorman:</strong>
  <%= @option.doorman %>
</p>

<p>
  <strong>House:</strong>
  <%= @option.house %>
</p>

<p>
  <strong>Apartment:</strong>
  <%= @option.apartment %>
</p>

<%= link_to 'Edit', edit_option_path(@option) %> |
<%= link_to 'Back', options_path %>